### ISSUE TITLE
1:N relations with arrays breaks the codegen

### ISSUE THREAD

**Issue by dpordomingo** [src-d/go-kallax#105]
Using 1:N relations with arrays breaks the codegen of the `kallax.go`

Given:
```
type Person struct {
	kallax.Model
	ID   kallax.ULID `pk:""`
	Pets [2]*Pet
}
```

The generated code is:
```
func (r *Person) NewRelationshipRecord(field string) (kallax.Record, error) {
    switch field {
    case "Pets":
        return new(2]*Pet), nil
    }
    return nil, fmt.Errorf("kallax: model Person has no relationship %s", field)
}
```

what does not compile cause `return new(2]*Pet), nil`

Tests in https://github.com/src-d/go-kallax/pull/106

## notice:
It is affected the Remove-Relation method too, when the relation is array-type. In that case, the generated remove method is "remove 1:1" kind, instead of  "remove 1:N" kind

**Comment by erizocosmico** [comment]
We decided to remove arrays as relationships and leave only slices in the end.
