### ISSUE TITLE
one to many queries are slow

### ISSUE THREAD

**Issue by erizocosmico** [src-d/go-kallax#110]
Returning 100 records containing 4 relationships each takes 7459848 ns/op, which is horribly slow considering previously this was orders of magnitude faster (and considering is almost twice what it takes for GORM to do the same).

We must have introduced some change that made this very slow. We have to take a look at it and solve it asap.

In the current benchmark it does not happen, needs investigation.

**Comment by erizocosmico** [comment]
Can't reproduce, closing for now.

**Comment by Serabe** [comment]
@erizocosmico have you seen this behaviour since then?

**Comment by erizocosmico** [comment]
Nope, but it needs some investigation that was never done, so I prefer keeping this around until such investigation takes place.

**Comment by erizocosmico** [comment]
Closing, will reopen once it happens again.
