### ISSUE TITLE
Add LIKE and SIMILAR operators

### ISSUE THREAD

**Issue by erizocosmico** [src-d/go-kallax#122]
Reference: https://www.postgresql.org/docs/9.6/static/functions-matching.html

* [x] `LIKE`
* [x] `ILIKE`
* [x] `SIMILAR TO`
* [x] `NOT SIMILAR TO`

**Comment by jorbs** [comment]
I just made a PR (https://github.com/src-d/go-kallax/pull/137) implementing LIKE operator.

**Comment by jorbs** [comment]
What about to implement `ILIKE`? As stated in the documentation "This is not in the SQL standard but is a PostgreSQL extension."

**Comment by erizocosmico** [comment]
True, ILIKE and ISIMILAR are missing.
On Wed, 26 Apr 2017 at 17:25, João Roberto <notifications@github.com<mailto:notifications@github.com>> wrote:

What about to implement ILIKE? As stated in the documentation "This is not in the SQL standard but is a PostgreSQL extension."

**Comment by jorbs** [comment]
Cool. I'm going to work on them separately.

**Comment by jorbs** [comment]
Are you sure PostgreSQL has `ISIMILAR TO` operator? I couldn't find it on the documentation.

**Comment by erizocosmico** [comment]
@jorbs nope, it does not, just checked. I replaced it with `NOT SIMILAR TO` in the todo list.

**Comment by erizocosmico** [comment]
Rest done in #143
