### ISSUE TITLE
Doesn't support GOPATH list

### ISSUE THREAD

**Issue by hectorj** [src-d/go-kallax#123]
Hi! I'm giving a test ride to Kallax and I hit my first minor bump in the road. It's not critical as there is an easy workaround (`export GOPATH=/my/first/go/path`), but it is an inconvenience.

As described [in the Go documentation](https://golang.org/cmd/go/#hdr-GOPATH_environment_variable), GOPATH can be a list (`:`-seperated on UNIX).

But currently the GOPATH is treated as a single value ([here](https://github.com/src-d/go-kallax/blob/master/generator/processor.go#L462) and [here](https://github.com/src-d/go-kallax/blob/master/generator/template.go#L433)).

In my env it generates errors like this : 
```bash
> echo $GOPATH
/my/first/go/path:/my/second/go/path
> go generate .
panic: open /my/first/go/path:/my/second/go/path/src/gopkg.in/src-d/go-kallax.v1/generator/templates/base.tgo: no such file or directory

goroutine 1 [running]:
gopkg.in/src-d/go-kallax.v1/generator.loadTemplateText(0x727b86, 0x12, 0x73a801, 0xc420049ed0)
        /my/first/go/path/src/gopkg.in/src-d/go-kallax.v1/generator/template.go:436 +0xe0
gopkg.in/src-d/go-kallax.v1/generator.makeTemplate(0x711a4e, 0x4, 0x727b86, 0x12, 0x1)
        /my/first/go/path/src/gopkg.in/src-d/go-kallax.v1/generator/template.go:448 +0x39
gopkg.in/src-d/go-kallax.v1/generator.init()
        /my/first/go/path/src/gopkg.in/src-d/go-kallax.v1/generator/template.go:457 +0x126
main.init()
        /my/first/go/path/src/gopkg.in/src-d/go-kallax.v1/generator/cli/kallax/cmd.go:80 +0x58
kallax.go:14: running "kallax": exit status 2
```

**Comment by erizocosmico** [comment]
Thanks for spotting this! Will get to it as soon as we can.

**Comment by hectorj** [comment]
Thanks!

I have a diff that fixes it but I haven't had the time to make it nice and clean.

Small note: I think https://golang.org/pkg/path/filepath/#SplitList is the recommended way of splitting $GOPATH

**Comment by erizocosmico** [comment]
If you're willing to send us the diff we can clean it and such, if you want.

**Comment by hectorj** [comment]
Sure, I'll make a PR with what I have tonight when I get home :+1:

**Comment by erizocosmico** [comment]
Great, thank you!

**Comment by hectorj** [comment]
PR submitted :slightly_smiling_face:
