### ISSUE TITLE
Running `Find` inside Transaction will panic due to `s.db` being `nil`

### ISSUE THREAD

**Issue by choonkeat** [src-d/go-kallax#132]
Reproduce

``` go
// store_test.go

func (s *StoreSuite) TestTransaction_Query() {
	err := s.store.Transaction(func(store *Store) error {
		q := NewBaseQuery(ModelSchema)
		q.Select(NewSchemaField("name"), ModelSchema.ID())
		_, err := store.Find(q)
		s.Nil(err)
		return nil
	})
	s.Nil(err)
}
```

The problem (I think) is that `newStoreWithTransaction` returns a `*Store` with `proxy` and `builder` set, `db` empty. Then in places like `Find`, `RawQuery` and `RawUpdate`, uses `s.db` directly.

I don't know `squirrel` enough, but can we simply swap out `s.db` with `s.proxy` instead?

**Comment by erizocosmico** [comment]
Thanks for reporting! will be fixing this ASAP.
