### ISSUE TITLE
Create and drop scripts

### ISSUE THREAD

**Issue by jorbs** [src-d/go-kallax#136]
Hi,

I'm planning to contribute with the create and drop database scripts. Initially, I thought to implement it as a `cli` command. Do you have any progress on this? Let me know your thoughts.

Cheers.

**Comment by jorbs** [comment]
The same idea could be applied to create/drop table.

**Comment by erizocosmico** [comment]
Hi there! Thanks for your interest in developing this.

We have not yet thought of how to implement this, since we have more impending issues to implement right now, but we're totally in if you want to tackle this. Let us have a bit of a discussion about how we want to fit this into the project and get back to you as soon as we can. Does that seem ok to you?

**Comment by jorbs** [comment]
So I have two points:
1. After I created this ticket I thought if create/drop database feature would be out of scope of an ORM. That's something I would like to discuss;
2. Create/drop tables is more important than 1. So I think in two ways to implement this:
  2.1. Implement a `cli` command. This would be a similar approach from Rails ActiveRecord `rake db:migrate` script;
  2.2. Passing parameters to the generator.

**Comment by Serabe** [comment]
Hi @jorbs:

We think that a migration tool is out of scope of kallax. That said, we are interested on integrating with one and we are trying to decide which, since we have a few available options.

We'll be talking about this at the end of next week (there are a few holidays here in Madrid now) but we would appreciate any feedback on known migration tools in Go. Have you used any of them or have gone through this process before?

Thank you!

**Comment by jorbs** [comment]
Hey @Serabe 

I said `rake db:migrate` as an (bad) example. But the migration itself (with `alter table`, `create index` commands) is out the scope for sure. The point is to implement a `cli` command that would read the table structure and then just create/drop it.

And I've never worked on any migration tools in Go.

Cheers.

**Comment by erizocosmico** [comment]
Hi @jorbs.

We've discussed this feature and we've decided to do the following:

- Use an existing tool to manage migrations.
  It needs to have the following things.
  - Usable programmatically.
  - Timestamp-based filename convention.
  - Provide up and down functionality.
  - Keep track of the current database version.

- Keep track of the model schema.
  - If there are no migrations, generate a schema for the whole model, with the create table and drop table. Save the lockfile of the migration.
  - If there are migrations, use the latest lockfile and diff the current model against that. The resultant migration is the diff between the lockfile and the model. 
  - Every single migration comes with 3 files:
    - Up SQL script: script to upgrade to that version from the previous one.
    - Down SQL script: script to downgrade from that version to the previous one.
    - Lockfile: JSON with the final schema of all models in this version.
  - Possible migrations:
    - New fields.
    - Fields removed.
    - Fields renamed.
    - New tables.
    - Tables removed.
  - Unhandled migrations:
    - Column type change: if a column type changes, the data migration is not trivial, and thus we will just print a warning message and urge the user to do that migration by themselves, as it is too complicated to do.

We want to track all the changes in a model, not only the create/delete script. This is a rather big task, so if you don't want to work on that we'd understand.

For now, we're starting to work on it and experimenting a bit with the lockfiles and such.

**Comment by jorbs** [comment]
@erizocosmico 

Those changes look good to me. But initially I thought only create and drop tables (by running a command). Yes, it looks like big to me, so I'll work on something different on this project.

Thank you for your feedback on this!

**Comment by erizocosmico** [comment]
Closing this in favor of #145
