### ISSUE TITLE
Add % operator

### ISSUE THREAD

**Issue by Niondir** [src-d/go-kallax#140]
My query looks like:

```
[...]
WHERE (name % ?)
```

where `?` is any search string. This query works with the full text search plugins of postgres. I would like to be able to use it with kallax. As of now I will try to build my own Condition.

**Comment by erizocosmico** [comment]
Hi! Thanks for raising the issue. Will add the operator asap.

**Comment by erizocosmico** [comment]
On a second thought, this is an operator of `pg_trgm` extension. I think it's out of the scope of kallax adding operators for extensions. At least in the core library.

**Comment by Niondir** [comment]
I would be happy with some documentation how to simply add my custom operator. Or allow some API for "non safe" plain SQL in my query builder.

**Comment by erizocosmico** [comment]
Fair point, we should make a nicer API to create custom operators and document how to do that.
