### ISSUE TITLE
Generating constraints

### ISSUE THREAD

**Issue by qJkee** [src-d/go-kallax#171]
Is it's possible to set constrains to fields,(for example 'unique') or I need to check that fields manually by defining methods such as `BeforeUpdate`?

**Comment by erizocosmico** [comment]
Right now there's no way to do that, but if you want to tackle that in a PR, it will be welcome'd!

If you're not using the migrations provided by kallax you can put that directly in your schema. If you are using them, you still can edit the SQL generated by kallax before running it, anyway.

**Comment by qJkee** [comment]
Hm, I think I can find time to look at your project and try to implement this feature =)

**Comment by erizocosmico** [comment]
Thanks! Just to give you some guidance, that would need to be struct tags, like 

```go
type Foo struct {
    SomeField int `unique:"true"`
}
```

**Comment by Niondir** [comment]
I could also need this feature. 

I guess the `lock.json` will also need some field `"Unique": true`

**Comment by Niondir** [comment]
I created this pr: https://github.com/src-d/go-kallax/pull/204

No test cases yet!

**Comment by erizocosmico** [comment]
@Niondir Thanks! yes, the lock would also need the unique field!
