### ISSUE TITLE
MultipleStores

### ISSUE THREAD

**Issue by qJkee** [src-d/go-kallax#175]
Hey! I'am using multiple stores in my project, and I want to knew.
Is each time when I call NewStore*(*sql.DB) it will open a new connection to db or pg driver will manage connections and use only limited pool of connections?

**Comment by erizocosmico** [comment]
All `New*Store` does is use the provided `*sql.DB`, if you give all the stores the same instance of `DB`, they will use just that one. `New*Store` does not create any connections by itself.

**Comment by qJkee** [comment]
And a new question)

From 1 table I have fk to another table, ex:

```
type ONE struct{
id int64
}

type TWO struct{
One  One `fk:"one_id"
} 
```

so, how can I get type Two, if I have ONE.ID?

**Comment by erizocosmico** [comment]
According to your model, `TWO` has an inverse key, so it would be like this:

```go
type ONE struct {
    kallax.Model
    ID int64 `pk:"autoincr"`
}

type TWO struct {
    kallax.Model
    One One `fk:"one_id,inverse"`
}
```

Note that a normal fk means the foreign key field is in the other model, if the foreign key is in the same model you need to use `inverse`.

After generating the code, you should have all this available:

```go
store := NewTWOStore(db)
two, err := store.FindOne(NewTWOQuery().FindByOne(one.ID))
if err != nil {
        // handle err
}
```

`FindByXXX` is generated for every relationship in a model. 

Hope this helps you!

**Comment by qJkee** [comment]
Sorry man, my bad, missed it in tutorial! Thanks!!!!!

**Comment by erizocosmico** [comment]
No problem! :)

**Comment by josephbuchma** [comment]
@erizocosmico is store instance thread-safe?
