### ISSUE TITLE
BenchmarkRawSQLQueryRelationships uses N+1 pattern

### ISSUE THREAD

**Issue by SlinSo** [src-d/go-kallax#178]
You are writing not to use the N+1 pattern because it can cause serious performance problems, but you are using this pattern for the raw SQL benchmark. That is not really a fair comparison.

You could use a single statement with a join. that would increase the resultset size.
or you could use the same pattern as kallax and use two statements.

**Comment by erizocosmico** [comment]
It's in the notes of the benchmark section in the README "Benchmark of database/sql for querying with relationships is implemented with a very naive 1+n solution. That's why the result is that bad."
