### ISSUE TITLE
Using kallax migrate command in Windows

### ISSUE THREAD

**Issue by pupkindt** [src-d/go-kallax#179]
kallax migrate up --dir ./migrations/ --dsn testing:testing@0.0.0.0:5432/testing?sslmode=disable --version 1497812710

returns

kallax: unable to open a connection with the database: parse file://d:\P\Go\pupkindt\src\ktest\migrations: invalid character "\\" in host name

Debugging shows that error appears in function getscheme. 
I think problem in using Parse from standard package net/url

The second issue is message "unable to open a connection with the database" - message must be about invalid --dir option

**Comment by erizocosmico** [comment]
Can you try now with version `v1.2.11`?

**Comment by pupkindt** [comment]
next iteration, result:

kallax: unable to open a connection with the database: open /d:/P/Go/pupkindt/src/ktest/migrations: the filename, directory name, or volume label syntax is incorrect.

May be problem in package github.com/mattes/migrate ?  

func New(sourceUrl, databaseUrl string) (*Migrate, error)
...
schemeFromUrl(sourceUrl)

// schemeFromUrl returns the scheme from a URL string
func schemeFromUrl(url string) (string, error) {
	**u, err := nurl.Parse(url)** // nurl "net/url"
	if err != nil {
		return "", err
	}
......
}

But url.Parse don't understand Widows path?

**Comment by erizocosmico** [comment]
OK, we'll investigate further this issue when we can find some time. Thanks!

**Comment by erizocosmico** [comment]
This is fixed by #194

**Comment by pupkindt** [comment]
Thank you!
