### ISSUE TITLE
Limit or offset number of results returned by `With{Type}`

### ISSUE THREAD

**Issue by roobre** [src-d/go-kallax#182]
It is stated in the documentation that filters (`kallax.Condition`) can be applied to  `With{Type}()` methods.

However, is it possible to apply offsets or filters to the rows joined by these functions? If so, what is the correct way of doing it?

Regards,
R

**Comment by erizocosmico** [comment]
Nope, there's no way to apply offsets and limits to the `With`s. That's by design. If you need to limit the results, it's not a relationship.

The ideal solution would be something like this:

```go
type A struct {
    ID int64
    B []*B
}

type B struct {
    ID int64
    A *A
}

records, err := bStore.FindAll(NewBQuery().FindByA(a.ID).Limit(10))
```

**Comment by roobre** [comment]
Nice, I'll go for that aproach then.

Thanks!

PD: ... which forces me to change from `Bs []B` to `Bs []*B`, if I want to keep marshalling simple. Not taking advantage of CPU cache makes me cry at night.

**Comment by erizocosmico** [comment]
No need, works with both `[]*B` and `[]B`. I put the `*` just because.

**Comment by roobre** [comment]
If I want to keep marshalling simple, this is, embedding the result of the "dependant" FindAll into `a`, I'd have to change it.

But anyway, as you said, when I have so many Bs, modeling the relation as `A has many Bs` feels unnatural. I'd rather model it as "B belongs to A", and query As separately.

Thanks for the advice!
