### ISSUE TITLE
PK issues

### ISSUE THREAD

**Issue by noonien** [src-d/go-kallax#186]
Hello!

I'd like to use kallax in my projects, however, I have some issues with doing this.

I prefer to have my models and store layer in different packages, I would like not to have kallax to import in the models package. I do this by having a new type in the store package for every model I need, for example:

```go
package models

type Foo struct {
	ID int `pk:"autoincr"`
	Bar string
	Baz string
}
```
```go
package kxstore
import (
	kallax "gopkg.in/src-d/go-kallax.v1"

	"my-project/models"
)

type Foo struct {
	kallax.Model `table:"foos"`

	models.Foo
}
```

When running `kallax gen`, i get the following message: `kallax: model Foo has no primary key defined`.

Also, some of my models don't have a primary key, does kallax not support models without ids?

**Comment by Serabe** [comment]
Hello @noonien,

If you want to have the model and store layer in different packages, why is the pk in the first one? We wanted to have the `pk` explicitly defined in the model to avoid collisions and multiple pk definitions. Furthermore, embedded structs embed the fields without namespacing them.

We are considering adding the `pk` struct tag for kallax.Model. Something like:

```go
type Foo struct {
    kallax.Model `table:"foos" pk:"ID,autoincr"`
    models.Foo
}
```

Would that solve your issue?

Thank you!

**Comment by noonien** [comment]
Hello @Serabe!

Ideally, kallax would not need a "pk" struct tag on a field named "ID", perhaps except to ignore it as PK.

I believe you can use [StructField.Anonymous](https://golang.org/pkg/reflect/#StructField) to check if it's an embedded field, eliminating and ambiguity and pk collisions, IMHO.

From what I can gather, "pk" is only used by kallax when it's defined as "autoincr", to automatically set the returned ID on the record after an INSERT. If this is the case, your suggestion would work just fine.

Preferably kallax would have autoincr the default behavior, and provide a way to define it as non-autoincr, but I guess this would not be possible due to backward compatibility reasons.

It would also be great if kallax would support models that do not have ids.

**Comment by erizocosmico** [comment]
Hello @noonien,

Regarding the implicit ID's, we prefer it to be explicit.
Also, there is no plan to support models with no primary keys for the time being since this is not a very common case.

The new version `v1.2.13` has been released allowing the definition of the primary key directly in the embedded `kallax.Model`. You can use it like this:

```go
type Foo struct {
    kallax.Model `table:"foos" pk:"id,autoincr"`
    models.Foo
}
```

Thank you!

**Comment by noonien** [comment]
Thanks, much appreciated!

Well, the actual problem I'm trying to solve is when models need multi-column PKs, which kallax does not support. It would be helpful to not be required to create 2 indexes when one is not really used.

**Comment by erizocosmico** [comment]
Multi-column PKs are definitely in the roadmap. We're thinking how to do that with the current architecture, so it might take a while, but it's in the roadmap.
