### ISSUE TITLE
The use of github.com/pkg/errors package is intended?

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-kallax#190]
There are some places into go-kallax that instead of use "errors" package, we are using the previous mentioned one, is this intended?

**Comment by erizocosmico** [comment]
The only place using `github.com/pkg/errors` is in the benchmark package for the generated code of SQLBoiler, which we cannot control. We do not use `pkg/errors` (or `src-d/errors` for that matter), we use plain ol' `errors` from standard library.
