### ISSUE TITLE
RemoveThings() does not delete related models

### ISSUE THREAD

**Issue by roobre** [src-d/go-kallax#192]
Given two models in a one-to-many relationship, calling

    store.Debug().RemoveBs(A)

does not output anything, and depending models are not deleted.

Calling `store.Debug().Delete(A)` fails due to fk constraint in the database, as Bs referencing A still exist.

Don't hestitate to ask for more details if the issue can't be reproduced at your side.

**Comment by erizocosmico** [comment]
Can you make a pull request adding a test that makes it fail for your case?

**Comment by roobre** [comment]
Hello there,

Can you provide some instructions for setting up the test environment?

I can figure out which credentials the `testing` database needs, but I have no clue about how to generate its schema.

**Comment by erizocosmico** [comment]
The tests themselves create their schema. All you need is a database named `testing` and a `testing` user with the password `testing`.

You can:

```
docker run -p 5432:5432 -e POSTGRES_PASSWORD=testing POSTGRES_USER=testing POSTGRES_DB=testing --name test-postgres -d postgres:9.6-alpine
```

If that is a problem, you can also change those values with environment variables:
https://github.com/src-d/go-kallax/blob/master/tests/common_test.go#L13-L17

**Comment by roobre** [comment]
Ok, I've found the bug.

On the generated code for RemoveThings, when checking if the len of things to remove is zero, the code does:

	if len(deleted) == 0 {
		clear = true
		deleted = record.Values
		if len(deleted) == 0 {
			return nil
		}
	}

However, if `record` wasn't queried with `WithThings()`, `record.Things` will be a nil slice, so it won't remove anything. Ideally, `RemoveThings()` should issue a reload if the slice if things to remove is nil, just to be sure.

In addition, also on this method, some weird checks are done:

	if len(deleted) > 1 {
            // iterate over deleted and remove
        } else {
            // same code but only for &deleted[0]
        }

I don't understand why this distiction is made, since an slice with one element should be iterated the same way an slice with > 1 elements is.

Regards, Roberto.

**Comment by erizocosmico** [comment]
Of course, if the Bs in A are not loaded, they will not be removed. That's not a bug, that's the expected behavior. Perhaps we should clarify that on the docs.

That last check is there because when there is just one element and it has no `AfterDelete` we can avoid making a transaction and just making a query. In any other case, a transaction is needed.

**Comment by roobre** [comment]
Nice. In that case, a hint on the docs would be appreciated then :D

I didn't think about the transaction thing, that's indeed a performance save worth doing.

Regards, R.
