### ISSUE TITLE
Automatic schema generation and migrations

### ISSUE THREAD

**Issue by Niondir** [src-d/go-kallax#193]
Hi,
it's already stated in the documentation that it will be implemented but I did not found any issue about the topic.

Are there already any thoughts about it? Would you generate SQL files or apply patches created with query builders directly to the DB like gorm does? Is there a rough schedule or prioritization?

Since there are already some SQL based migrations tools, can you recommend something until the Kallax support is implemented?

**Comment by erizocosmico** [comment]
Hi, migrations were implemented a couple months ago, here's the full documentation about it: https://github.com/src-d/go-kallax#migrations

Did you find in any part of the docs that migrations are not yet implemented? Maybe there's some part that's outdated.

**Comment by Niondir** [comment]
I got confused by the Readme where you have a dead link in the index named "Automatic schema generation and migrations". I found the documentation to generate migrations. Just facing some windows issues now (see: https://github.com/src-d/go-kallax/issues/194).

**Comment by erizocosmico** [comment]
Just fixed the readme, thanks for reporting!
