### ISSUE TITLE
Kallax migrate does not work on windows

### ISSUE THREAD

**Issue by Niondir** [src-d/go-kallax#194]
I found that migrate will prepend a "/" to the path in `pathToFileURL`. This does not work for windows environments, resulting in the following error:

`kallax: unable to open a connection with the database: open /C:/dev/gopath/src/github.com/my-project/migrations: The filename, directory name, or volume label syntax is incorrect.`

Why not just rely on the Go API and use `filepath.ToSlash()`

**Comment by Niondir** [comment]
Since the migrate tool is pretty simple I just wrote my own as part of my server application. 

This way loading the path on windows works fine, I do not see why it should fail on Linux this way:

```
func RunMigrate(cmd *cobra.Command, args []string) {
	dbConfig := MustLoadConfig()
	dsn := dbConfig.ConnectionString()
	dir := viper.GetString("dir")

	if !filepath.IsAbs(dir) {
		dir, _ = filepath.Abs(dir)
	}
	dir = filepath.ToSlash(dir)
	dir = "file://" + dir
	logrus.WithField("dir", dir).WithField("dsn", dsn).Info("Run Migration...")

	m, err := migrate.New(dir, dsn)
	if err != nil {
		logrus.WithError(err).Fatal("Failed to create migration")
	}

	err = m.Up()
	if err != nil {
		logrus.WithError(err).Fatal("Failed to migrate database")
	}
}
```

**Comment by erizocosmico** [comment]
Thank you for the report, we'll look into this as soon as possible.

**Comment by erizocosmico** [comment]
@Niondir can you confirm the latest release fixes this issue?

**Comment by Niondir** [comment]
Seems to work: `kallax migrate --input ./backend/model/ --out ./migrations --name initial_schema`
