### ISSUE TITLE
Migration generates nullable columns

### ISSUE THREAD

**Issue by Niondir** [src-d/go-kallax#198]
Is it expected behavior that 

```
type User struct {
	kallax.Model `table:"users" pk:"id"`
	ID           kallax.ULID
	Username     string
	Email        string
	Password     string
}
```

Results in all columns nullable

```
CREATE TABLE users (
	id uuid PRIMARY KEY,
	username text,
	email text,
	password text
);
```

Same for non pointer structs.

**Comment by erizocosmico** [comment]
Right now it does, but maybe it should make them all not nullable unless it's a pointer. What do you think, @Serabe?

**Comment by Niondir** [comment]
That's at least what I would expect.
