### ISSUE TITLE
types/types_test TestNullable failes locally on windows

### ISSUE THREAD

**Issue by Niondir** [src-d/go-kallax#203]
> Error Trace:	types_test.go:434
> 	Error:		Not equal: 
> 			expected: time.Time{sec:63635636271, nsec:0, loc:(*time.Location)(nil)}
> 			received: time.Time{sec:63635636271, nsec:0, loc:(*time.Location)(0xc04203b3e0)}
> 			
> 			Diff:
> 			--- Expected
> 			+++ Actual
> 			@@ -1,2 +1,2 @@
> 			-(time.Time) 2017-07-14 13:37:51 +0000 UTC
> 			+(time.Time) 2017-07-14 15:37:51 +0200 CEST
> 			 
> 	Messages:	time.Time

**Comment by roobre** [comment]
I have no means to test or fix this, as I don't have windows machines. PRs are welcome.

**Comment by smola** [comment]
This fails on macOS too:

```diff
--- Expected
+++ Actual
@@ -1,2 +1,2 @@
-(time.Time) 2018-05-17 17:07:56 +0000 UTC
+(time.Time) 2018-05-17 17:07:56 +0000 GMT
```

See a failing macOS build here: https://travis-ci.org/src-d/go-kallax/jobs/380310885#L1042 (requires https://github.com/src-d/go-kallax/pull/268)

**Comment by smola** [comment]
When creating the date, I guess we have to force it to UTC (with `.UTC()` function?), since each operating system translates the `+0000` offset to a different timezone by default. I guess this could even happen on Linux in some setups.
