### ISSUE TITLE
Partial update does not set `updated_at` column

### ISSUE THREAD

**Issue by jBugman** [src-d/go-kallax#224]
Given model with embedded `kallax.Timestamps` and update of the kind `store.Update(x, model.Schema.X.FieldY)` column `field_y` does change, but column `updated_at` does not.
Is it intended? If it is it should be documented.

**Comment by roobre** [comment]
This should be being done on the `BeforeSave()` event you embed with `kallax.Timestamps`. Does your model have its own `BeforeSave()` by chance?

If so, the solution should be calling `kallax.Timestamps.BeforeSave()` on your own `BeforeSave()`.

**Comment by roobre** [comment]
Closing due to lack of response from the OP.
