### ISSUE TITLE
Nullable fields

### ISSUE THREAD

**Issue by qJkee** [src-d/go-kallax#228]
You say that all fields are nullable, but now I got error

sql: Scan error on column index 4: unsupported Scan, storing driver.Value type \u003cnil\u003e into type *string

**Comment by Niondir** [comment]
Same here, getting an error for nil-able string columns.

`sql: Scan error on column index 6: unsupported Scan, storing driver.Value type <nil> into type *string`

**Comment by Niondir** [comment]
I get the same error when having a `string` field but the database has a `null` value. IMHO the value should be loaded as empty string in Kallax instead of throwing an error.

**Comment by roobre** [comment]
Right now, db NULLs are translated to `nil` if go type is nullable (aka pointers). So `*string` should be set to NULL if set on the database, but trying to scan `NULL` into `string` (no pointer) should throw an error.

@qJkee Could you provide the code triggering this behaviour? This is, your model definition and how are you retrieving the data.

**Comment by qJkee** [comment]
`type Account struct {
	kallax.Model  `table:"account"`
	ID            int64 `pk:"autoincr"`
	Name          string
	IconURL       string
	RefuseComment string
}`

For example, if RefuseCimment is null, it causes error

**Comment by roobre** [comment]
Try changing `RefuseComment string` to `RefuseComment *string`.

**Comment by qJkee** [comment]
So, is it possible to set default values instead of returning an error? As I knew, that was that before

**Comment by roobre** [comment]
You might want to give [custom constructors](https://github.com/src-d/go-kallax#model-constructors) a try. I'm not sure if they will work on all queries, tho.

**Comment by qJkee** [comment]
looks like this is the only solution, coz if I use pointers, I will  get a segfault when accessing field, which is a null pointer

**Comment by roobre** [comment]
Well, a database NULL is translated to a nil pointer, yes. This is the expected behaviour. Using NULL as an alias for some default value is a terrible practice. Maybe in the future, when schema generation gets improved, we can add some support for default values via struct tags.

I'm closing this. Feel free to reopen if some other unexpected behaviour appears.
