### ISSUE TITLE
Kallax generates broken code if a relationship is not a pointer

### ISSUE THREAD

**Issue by roobre** [src-d/go-kallax#234]
Mostly what the title said. It can be worked around by making them pointers, but that will loose the restriction of the relationship not being nullable (which, I think, its a bad way of specifying that and a tag should be used insted).

The error occurs at the generated `inverseRecords` function, which on its sixth line calls `Save(record.RelatedThing)`. This does not compile as `record.RelatedThing` is not a pointer.

Code generation is a bit beyond my expertise level with go, so I'm afraid I won't be able to write a PR with a test case for this.

I can provide some example code if you can't reproduce the issue.

**Comment by qJkee** [comment]
Same here
./kallax.go:620:48: cannot use record.Account (type Account) as type *Account in argument to (&AccountStore literal).Save
