### ISSUE TITLE
Code generation does not work

### ISSUE THREAD

**Issue by josephbuchma** [src-d/go-kallax#235]
I've done everything as described in readme, but `kallax gen` does not work.
go 1.8, ubuntu. 
Output from `kallax gen`:
```
Package: models
Model: "User" [7 Field(s)] [Events: [BeforeSave]]
```
That's it, no evidence of generated `kallax.go`

**Comment by roobre** [comment]
Probably you are getting an error, but it's not getting print due to #225. This is just a guess tho. Can you post your models here?

**Comment by josephbuchma** [comment]
Found problem, my PK was not int64. And yeah, output is not very helpful.
I see commit https://github.com/src-d/go-kallax/commit/77b51c37c85b9036c6f0dad9bfb436f239bc91e1 "implement customizable primary key types" but it seems to be undocumented.

**Comment by chenkaiC4** [comment]
@roobre this is my model, any help?

```
package models

type User struct {
	kallax.Model `table:"users" pk:"id"`
	ID           kallax.ULID
	Username     string
	Email        string
	Password     string
}

//go:generate kallax gen
```

after exec `kallax gen`, nothing happend!

computer setting
- go 1.9,
- os macox 10.12.6

**Comment by josephbuchma** [comment]
@chenkaiC4  until #227 is merged, you can copy changes from there and recompile your kallax binary. 

BTW, @roobre why it's not being merged yet?

And, @chenkaiC4 :
1) Make sure you run `kallax gen` inside your models directory, or use `--intput` and `--output` flags. 
2) Put `// go:generate kallax gen` at the top of this file if you plan to use `go generate`

**Comment by chenkaiC4** [comment]
@jorgeschnura thank, i will have a try~

**Comment by chenkaiC4** [comment]
@josephbuchma i have recompile kallax, now the err is printed:

`file.go:6:2: undeclared name: kallax`

my modle file `file.go`

```
// go:generate kallax gen
package models

type User struct {
	kallax.Model `table:"users" pk:"id"`
	ID           kallax.ULID
	Username     string
	Email        string
	Password     string
}
```

any suggestion ?

**Comment by chenkaiC4** [comment]
@josephbuchma  i have get it done.  thank your very much!


this is my model file now, give other people a example:

```
package models

import (
	"errors"
	"gopkg.in/src-d/go-kallax.v1"  // don't forget to import
)

type File struct {
	kallax.Model `table:"files" pk:"id"`
	ID           int64
	Name         string
}

func new(name string) (*File, error) {
	if name != "" {
		return nil, errors.New("file name are required")
	}

	return &File{Name: name}, nil
}
```

**Comment by chenkaiC4** [comment]
@josephbuchma one more question.

where to set the postgres connection settings ? the generator file only have lots of methods,
don't have a method like 'connect' to supply my database address.

**Comment by chenkaiC4** [comment]
@josephbuchma i think i find the method to connect to database, the document isn't show us this.

every model will have `NewModelStore` function to give the functional instance which has the `Update`, `Insert` etc function for usage.

![image](https://user-images.githubusercontent.com/7543145/30588791-b3572ab6-9d6a-11e7-8a1d-5e83318b85c1.png)

**Comment by roobre** [comment]
@chenkaiC4 As you said, models are manipulated using stores, which are generated by kallax gen, one for each model. From the readme:

* A store named `{TypeName}Store`: the store is the way to access the data. A store of a given type is the way to access and manipulate data of that type. You can get an instance of the type store with `New{TypeName}Store(*sql.DB)`.

You can get an `*sql.DB` from `sql.Open()` (`sql.Open("postgres", ...`)

@josephbuchma Unfortunately I don't have mantainer rights on this repo. I just happen to have one or two PRs accepted here. Sorry :(

**Comment by chenkaiC4** [comment]
@roobre thanks for your tips, i should have read the doc more carefully.

**Comment by roobre** [comment]
No problem :D

To be honest, I missed that too when I read it for the first time. Perhaps it should be more visible.

Anyway, I guess we can close this?

**Comment by josephbuchma** [comment]
Think so. Hope fix will be merged soon.
