### ISSUE TITLE
As mantainers have apparently abandoned the project, I'm forking this to allow bug-fixing PRs

### ISSUE THREAD

**Issue by roobre** [src-d/go-kallax#238]
Mostly what the title says. I'm not a core developer here, so most likely I won't be able to provide more than basic support, let alone implementation of new features. But at least community-made PRs will be tested and merged.

If the mantainers eventually return, I'd be happy to make another PR from my fork to this.

My fork: https://github.com/roobre/go-kallax

**Comment by qJkee** [comment]
Hey! I'm also using this orm, so i will try to help you to fix all issues and make your fork better

**Comment by roobre** [comment]
Awesome! :D

**Comment by xserve98** [comment]
@roobre   is store instance thread-safe?

**Comment by roobre** [comment]
I have no idea, to be honest. AFAIK, databases are naturally thread-safe, so it wouldn't be a problem for that part. However, stores do set some flags on objects when they're being saved, presumably without setting any mutexes. So I'd say manipulating the same model instance in multiple routines is indeed **not safe**. However, using the same store instance with different models **probably is**.

Please note that I didn't author this code, this is just my interpretation after flipping through the code.

**Comment by roobre** [comment]
Status update: I'll help maintaining this project here, so I'll close my own fork and merge & fix stuff here.
