### ISSUE TITLE
Ordering from variable

### ISSUE THREAD

**Issue by nikkon226** [src-d/go-kallax#240]
I want to be able to implement ordering based on user input from GET request params.

Easy enough to use a switch statement with different cases, but here is the problem I ran into: I want to order based upon information in a JSON field. Currently, there is no way to do this because of private functions in the interface.

The way I went about solving this is to use a custom type for column sorting and implement the interface for [ColumnOrder](https://github.com/src-d/go-kallax/blob/80487620b6c62eb3f558bf9863be31842912dd47/query.go#L288). I cannot implement the interface because it requires `kallax.isColumnOrder()` which I cannot make a function in my code like this.

Please change this function to a public function so that we could implement our own sort order names.

** Ordering based on JSON fields are simple `ORDER column->>'jsonKey' ASC` for example.

**Comment by roobre** [comment]
You need to embed the `ColumnOrder` interface in your own struct, and then define `ToSql(Schema) string` as usual:

```go
type jsonOrder struct {
    kallax.ColumnOrder
    // any other stuff in case you need it
}

func (jso *jsonOrder) ToSql(Schema) string {
    // do even more stuff
}
```

Please note that I haven't tested this, but technically it should work.

**Comment by Julusian** [comment]
Embedding ColumnOrder like that is possible.
I have used the same method to achieve random ordering: https://github.com/src-d/go-kallax/issues/221

**Comment by nikkon226** [comment]
I changed my code to reflect this idea and it works. I'm still relatively
new to go, so I'm learning.

Thanks for the help!

**Comment by nikkon226** [comment]
Closing issue based on the above (no problems, just noobish).
