### ISSUE TITLE
IS NULL check

### ISSUE THREAD

**Issue by josephbuchma** [src-d/go-kallax#244]
How to make null check with kallax? 
I'm looking for something like
```go
NewSubscriptionQuery().Where(kallax.IsNull(Schema.Subscription.UnsubscribedAt))
```

**Comment by josephbuchma** [comment]
As I see from squirrel docs `Eq(schema.Field, nil)` should work

**Comment by roobre** [comment]
Closing as it has been (auto) resolved. Feel free to reopen if it doesn't work.
