### ISSUE TITLE
unexpected directory layout during go get

### ISSUE THREAD

**Issue by agnivade** [src-d/go-kallax#247]
```
$go get -u gopkg.in/src-d/go-kallax.v1/...
unexpected directory layout:
	import path: github.com/mattn/go-colorable
	root: /home/agniva/play/go/src
	dir: /home/agniva/play/go/src/github.com/fatih/color/vendor/github.com/mattn/go-colorable
	expand root: /home/agniva/play/go/src
	expand dir: /home/agniva/play/go/src/github.com/fatih/color/vendor/github.com/mattn/go-colorable
	separator: /
```

Am I dong something wrong ?

EDIT - I have Go 1.9.2 linux/amd64

**Comment by roobre** [comment]
It looks like a [faith/color](https://github.com/fatih/color) issue to me.

**Comment by agnivade** [comment]
I can do a go get of fatih/color just fine. And a simple go get of `gopkg.in/src-d/go-kallax.v1` also works fine. Only when I try to get the internal packages with `/...`, it fails.

**Comment by agnivade** [comment]
I had to import the `generator/cli/kallax` package manually and then running it again worked. Strange.
