### ISSUE TITLE
generate does not work upon pointer change

### ISSUE THREAD

**Issue by agnivade** [src-d/go-kallax#248]
If I have a model like this - 

```go
type User struct {
	kallax.Model `table:"users"`
	ID           int64 `pk:"autoincr"`
	Username     string
	Email        string
	Password     string
	CreatedAt    time.Time
}

type Card struct {
	kallax.Model `table:"cards"`
	ID           int64 `pk:"autoincr"`
	User         User `fk:"user_id,inverse"`
	Number    string
}
```
for which the code is already generated.

Now, if I make the `User` field to be a pointer. And then run `go generate ./...`. It gives an error like - 
```
kallax.go:84:12: cannot use *val (variable of type User) as *User value in assignment
model/model.go:1: running "kallax": exit status 1
```

But if I delete the `kallax.go` file and run `go generate ./...` again, everything works fine.

Same happens in the reverse order too. If I have a pointer field and then I remove the pointer and generate, it gives the same error.

Seems like a bug to me. If the `go generate` method is idempotent, shouldn't it automatically delete the `kallax.go` file and re-generate. Why does having an existing file return an error ?

**Comment by roobre** [comment]
Go generate tries to build your whole package first, then generate the files. As the old `kallax.go` is incorrect, your package never builds, so the new `kallax.go` is not generated.

`go generate` is certainly not idempotent, at least not in kallax. I don't know if it should be, honestly. Do you have any sources about this idempotency thing?

**Comment by agnivade** [comment]
I see. Do you have any reason for why it should _not_ be idempotent ? I mean, if deleting the kallax.go file and running `go generate` always works, then shouldn't `kallax gen` take care of deleting the file and generating it afresh ?

So, you are saying in a scenario like this, I need to delete my `kallax.go` and run `go generate` again ? What if I always delete `kallax.go` before running `go generate` ? Will that be harmful in any way ?

**Comment by ligustah** [comment]
Unless the package that you run `go generate` in directly depends on any of the code in the `kallax.go` file deleting it shouldn't cause any issues. IMHO it's not the responsibility of kallax to do that for the user.

**Comment by roobre** [comment]
Maybe we can address this in the future, as deleting the self-generated file before processing doesn't seem to be harmful. I'll take a look at it.
