### ISSUE TITLE
UUID pointer is never nil

### ISSUE THREAD

**Issue by kaasasolut** [src-d/go-kallax#252]
Here is an example to demonstrate the issue:
```go
package main

import (
	"database/sql"
	"fmt"

	_ "github.com/lib/pq"
	uuid "github.com/satori/go.uuid"
	"gopkg.in/src-d/go-kallax.v1"
)

type test struct {
	kallax.Model
	ID   int64 `pk:"autoincr"`
	UUID *uuid.UUID
}

func main() {
	db, _ := sql.Open("postgres", "postgres://testing:testing@0.0.0.0:5432/testing?sslmode=disable")

	t := NewtestStore(db).MustFindOne(NewtestQuery().Where(kallax.Eq(Schema.test.UUID, nil)))

	if t.UUID == nil {
		fmt.Println("UUID is nil")
	} else if *t.UUID == uuid.Nil {
		fmt.Println("UUID is a pointer to something equal to uuid.Nil")
	} else {
		fmt.Println("UUID is", t.UUID)
	}
}
```
If nothing panics, the expected result is `UUID is nil`.  
But the actual result is `UUID is a pointer to something equal to uuid.Nil`.  
It's the same with `*kallax.UUID`.

**Comment by roobre** [comment]
I've been searching the kallax sources but I don't seem to find anything which can explain this special behaviour. This probably is related to [pq](https://github.com/lib/pq) instead, or even deeper .

Also note that the [UUID RFC](https://www.ietf.org/rfc/rfc4122.txt) states what a "Nil uuid" is (4.1.7), so probably whoever is doing this translation is doing so because of this specification.

Switching to a more pragmatic point of view, why is this an inconvenience to you?

**Comment by kaasasolut** [comment]
The most significant inconvenience was the inconsistent behavior.
It took me a while to figure out why my code bugged. I was expecting, like on other types, that the pointer becomes `nil` if the value in the database is `NULL`.

There might be another issue, but I didn't test it yet. I've just got the idea while writing this.
What happens if I save such a struct without changing the UUID? Will it save `NULL` or the zero UUID into the database?

**Comment by roobre** [comment]
`UUID` is defined as a 16-byte array, so it's zero value should be `{0, 0, ... 0}`.

Again, I'm not sure why is this translation done, but I'm pretty sure it's not Kallax' responsibility. I advise you to stop using nullable `UUID` fields btw, it goes against the standard and it's kind of a weird practice.

**Comment by kaasasolut** [comment]
Okay. Would you kindly document this unusual behavior of UUID? I don't want that other persons waste their time as I did.

**Comment by roobre** [comment]
You have a point there, even if it is not a Kallax issue, it might seem important enough to be noted somewhere.
