### ISSUE TITLE
Support for Upsert on PG?

### ISSUE THREAD

**Issue by xserve2018** [src-d/go-kallax#253]
Hi,

Was using it for the past day or so and was wondering if there is a support for the Postgresql's Upsert [ON CONFLICT](https://www.postgresql.org/docs/9.5/static/sql-insert.html#SQL-ON-CONFLICT) statements.

**Comment by xserve2018** [comment]
@roobre

**Comment by kaasasolut** [comment]
[`Save`](https://github.com/src-d/go-kallax#save-models) is the Upsert of Kallax, isn't it?

**Comment by roobre** [comment]
`Save()` does not translate into an `INSERT ... ON CONFLICT DO UPDATE`, but the provided functionality is similar.

From reading postgres docs, I can see one big difference: Kallax' `Save()` checks if the model has already been inserted beforehand using an internal flag, and acts in consequence. SQL instruction, however, actually tries to insert the data first, and if an error occurs, then tries to update.

I'd recommend to check for specific errors in cases you suspect the insert/update will fail. Or even better, try to `Find()` conflicting models beforehand. Anyway, this is just for precaution, if you use kallax's schemas this conflicts should never occur, as there are no indexes apart from the PK, which is already checked by `Save()`.

**Comment by xserve2018** [comment]
thank you
