### ISSUE TITLE
Disabling prepared statements for pgbouncer support

### ISSUE THREAD

**Issue by film42** [src-d/go-kallax#256]
Hey there!

I see go-kallax is using squirrel's statement cacher, which is a good thing, but will not work when using pgbouncer in transaction pooling mode. The lib/pq maintainers have added support to pass `binary_parameters=yes` to disable prepared statements for this very reason. However, the statement cacher explicitly uses a prepared statement for each query, which isn't something lib/pq can work around. Would you consider accepting a patch that optionally disables the statement cacher to avoid prepared statements to work with pgbouncer in transaction pooling mode? If so, I'll get right on it. Thanks!

cc @roobre

**Comment by roobre** [comment]
Hi, thanks for your suggestion.

First of all I'd need some background on what is pgbouncer exactly, and what are the benefits/use cases for it (to get an idea of how it would benefit kallax).

Then I'll need to evaluate how much this would impact kallax' codebase. If it's just setting a flag here and there there would be no problem for me. If we have to manually check for this in several places, then it would be more complicated.

Please tell me what you think about these two points.

**Comment by film42** [comment]
Hey @roobre . pgbouncer is a database connection pooler. It's very common in ruby shops because ruby on rails tends to opens one DB connection for each request thread, but hardly ever saturates those connections. Since db connections are very expensive, pgbouncer is often used in "transaction pooling" which allows rails to "think" it's speaking with postgres the whole time, but pgbouncer will only checkout a real db connection for the duration of some statement or transaction. There's a catch to transaction pooling though, and that's that [prepared statements won't work unless we keep track of them manually](https://pgbouncer.github.io/faq.html#how-to-use-prepared-statements-with-transaction-pooling) and they recommend disabling them on the client side. There are many other reasons shops will us pgbouncer, such as being able to pause connections to failover a db with minimal downtime. We use pgbouncer primarily because of ruby, but the added tools have proved to be very useful.

Since our shop uses pgbouncer with transaction pooling, it would be nice to be able to disable the statement cache (which explicitly uses prepared statements). I'm hoping the implementation is as simple as adding a single flag to turn:

**Comment by roobre** [comment]
Looks like we can simplify the first point like this:

```go
func NewStore(db *sql.DB) *Store {
	builder := squirrel.StatementBuilder.PlaceholderFormat(squirrel.Dollar).RunWith(db)
	if enableCaching { // get this somewhere
		builder = builder.RunWith(squirrel.NewStmtCacher(db))
	}
	return &Store{
		db:      db,
		proxy:   proxy,
		builder: builder,
	}
}
```

as `StatementBuilderType.RunWith()` seems to be idempotent. This way, new stores will automatically inherit the proxy (when #254 gets fixed and merged).

Regarding WHERE the flag should be specified... it's more tricky. Of course, adding an additional parameter to NewStore is a no-no. We could, however, add `func NewStoreWithCaching(db *sql.DB, enableCaching bool) *Store` and make `NewStore(db *sql.DB)` call `NewStoreWithCaching(db, true)`.

This way we can avoid adding new flags to `Store`, which I think it shouldn't be avoided as caching is transparent to squirrel.

Tell me what you think about this approach. Take in mind, however, this would have to wait until #254 gets fixed (which will hopefully be soon (this week maybe)).

**Comment by roobre** [comment]
Fixed in https://github.com/src-d/go-kallax/commit/75a61190be346416056d88c21e932eea39f62ae7.

**Comment by film42** [comment]
Woo hoo! 

@roobre Looks like you might need to make one more small change here: https://github.com/src-d/go-kallax/blob/75a61190be346416056d88c21e932eea39f62ae7/store.go#L495 

to

```go
	txStore := (&Store{
		db:        tx,
		logger:    s.logger,
		useCacher: s.useCacher,
	}).init()
```

**Comment by roobre** [comment]
Woops, totally missed it.

**Comment by film42** [comment]
@roobre I think we're going to need to add these methods to the generator for the same reasons `Debug` and `DebugWith` were added to the generator. Without them something like
```go
var userStore *models.UserStore
userStore = models.NewUserStore(db).DisableCacher()
userStore.WithClient() // etc...
```
doesn't work.

I can work around it, but it should probably be added before a stable release.

**Comment by roobre** [comment]
The generator is being looked into due to #248, I'll add the method there after fixing it hopefully tomorrow, probably this week :)

**Comment by roobre** [comment]
Added to template in https://github.com/src-d/go-kallax/commit/bde8b21dcdcaee93c37a2187d141bcaf171cffd0.

**Comment by film42** [comment]
Been using master and so far it's working very nicely! Thanks @roobre . I did find one bug though.

When using `someStore.DisableCacher().Debug()` I end up with this error:
```
no Runner set (RunWith)
```

**Comment by roobre** [comment]
That doesn't sound good, let me take a look at it.

**Comment by roobre** [comment]
> When using someStore.DisableCacher().Debug() I end up with this error:

This seems to be both a bug and a very bad design from squirrel. `RunWith()` accepts a `squirrel.BaseRunner`, but then is type-asserted somewhere, and if it doesn't implement certain other interfaces (namely `squirrel.Runner`), it ends up returning nil. I've workarounded this by copypasting one dumb wrapper from squirrel and now it should work as expected.

**Comment by film42** [comment]
@roobre Just pulled in the latest changes. Everything looks great on my end. Thanks for the help!

**Comment by roobre** [comment]
Nice to hear that!

I'll release next monday/tuesday.
