### ISSUE TITLE
support `string` as an allowed pkey type.

### ISSUE THREAD

**Issue by amattn** [src-d/go-kallax#260]
I'm dealing with an api that uses strings (sometimes UUIDs, sometimes not) as primary keys.

I'd like to be able to model this in kallax.

Is there a specific reason that pk is limited to int64, UUID and ULID types?

**Comment by roobre** [comment]
Strings should not be used as primary keys in any relational database. I'm sorry if you have to deal with a setup like that, but we should not encourage this kind of bad design.

**Comment by amattn** [comment]
Thank you for considering.  I'll work around it somehow.
