### ISSUE TITLE
Change table's name of a model without make it explicit over tags

### ISSUE THREAD

**Issue by ifreddyrondon** [src-d/go-kallax#261]
Hi, is it possible to change the name of the table of a model without make it explicit over the tags of the struct ?

Context:
I want to use kallax in one of my projects, and that particular project has many integration test with the db, to be able to run these test in parallel and avoid long CI times I change the table name where the model lookup for data in every the test.

e.g
gorm.DB from GORM has a method Table() witch receives a string (name of the table) and return  *gorm.DB. Every operation made in the last *gorm.DB take always the table given as parameter

**Comment by roobre** [comment]
Hi,

I'm afraid it is not possible at the moment. Sorry for the inconvenience.
