### ISSUE TITLE
How to write join query using kallax

### ISSUE THREAD

**Issue by maheshjadav** [src-d/go-kallax#274]
Hello

i have to xyz table in which i store pqr table id.. now i want pqr table name field value .. how can i write join query.. i got list of xyz table using kallax..

**Comment by maheshjadav** [comment]
if anyone having idea then please let me know

**Comment by roobre** [comment]
See: https://github.com/src-d/go-kallax#query-with-relationships

**Comment by maheshjadav** [comment]
from that i did not get name field value.. i have sms table where i store id,status(id of status table) and in status table i stored (id,name).. now i want relationship so when i generate code using kallax i got name filed value while listing sms table
