### ISSUE TITLE
Support Cockroachdb

### ISSUE THREAD

**Issue by gedw99** [src-d/go-kallax#282]
It should be relatively easy to support Cockroachdb.

How to with GORM
https://www.cockroachlabs.com/docs/stable/build-a-go-app-with-cockroachdb-gorm.html

Examples
https://github.com/cockroachdb/examples-orms

The cockroach team are pretty approachable and i bet would love to have a better ORM than GORM...

**Comment by roobre** [comment]
Hi,
Thanks for your interest and feedback. For now, kallax is pretty tied and tailored to postgres, and decoupling it and removing postgres-only idioms seems desirable, but hard enough to see it for the distant future. Sorry for the inconvenience.
