### ISSUE TITLE
Quote field and table name

### ISSUE THREAD

**Issue by Wayt** [src-d/go-kallax#284]
Hello folks,

I've encounter an issue while using kallax, some field / table in my database are using camelCase naming (unfortunately).

squirrel doesn't support field and table name escaping, see https://github.com/Masterminds/squirrel/issues/94

For example, with this table:
```
CREATE TABLE "companyUsers" (
	"id" bigint PRIMARY KEY     NOT NULL,
	"userName" varchar(255)     NOT NULL
);
INSERT INTO "companyUsers" ("id", "userName") VALUES (1, 'Hello World');
```

And model declared as follow:
```
type User struct {
	kallax.Model `table:"companyUsers" pk:"id"`
	ID           int64
	Username     string `kallax:"userName"`
}
```

code gives me:
```
func main() {
[...]
	u, err := NewUserStore(db).Debug().FindOne(NewUserQuery().FindByID(1))
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("%+v\n", *u)
}
```
```
2018/07/27 21:36:53 kallax: Query: SELECT __user.id, __user.userName FROM companyUsers __user WHERE __user.id IN ($1) LIMIT 1, args: [1]
2018/07/27 21:36:53 pq: relation "companyusers" does not exist
```

Same goes for column `userName`.

I've made a small change in kallax in order to support this, https://github.com/Wayt/go-kallax/commit/8a267400bd3c63ac72e819ee4f3785ba77a629a6
but I'm not sure of the impact on other database than Postgres.

What do you think ? Is it something that could be integrated into kallax ?

**Comment by Wayt** [comment]
Hello @roobre 

no this table wasn't created by kallax in first place.

I've hit this issue while trying to use kallax on existing database.
Is it out of scope for kallax ?

**Comment by roobre** [comment]
Hi,

Not necessarily out of scope, but it gets less priority since the bug is not entirely kallax' responsibility.

Anyway, your fix looks small and concise, however I'm not sure if this could affect existing databases, or cause unneeded migrations for adding quotes here and there. Please, create a PR so we can get some automated tests done. After that, probably manual testing is required to ensure it doesn't break migrations.

**Comment by Wayt** [comment]
Sure will do.

Thanks!
