### ISSUE TITLE
Filter based on related tables' columns not working

### ISSUE THREAD

**Issue by maheshjadav** [src-d/go-kallax#287]
Hello

i have this code

	q := models.NewCustomerQuery().
		WithStatus_().
                Where(kallax.Eq(models.Schema.Status.Name,"active"))

but it is not working instead of status.name it's give's customer.name when i debug query

**Comment by roobre** [comment]
Hello,

This operation is currently unsupported. You can workaround this issue by querying `Status` and requesting their associated customers.

Or perhaps flatten the design a bit and putting the status text as a field on customer, storing only secondary fields on the status struct. But of course this is only a suggestion.
