### ISSUE TITLE
[]byte fields get overwritten with random data when updating a model

### ISSUE THREAD

**Issue by hayeah** [src-d/go-kallax#298]
Version: v1.3.5

[See fix below](https://github.com/src-d/go-kallax/issues/298#issuecomment-435564130) 

I have cooked up a [minimal test case](https://github.com/hayeah/go-kallax-bug). 

The test will increment `Counter` by 1, and we expect that `Data` and `Data2` would remain the same after the update.

```go
type TestModel struct {
	kallax.Model `table:"test_models"`
	ID           int64 `pk:"autoincr"`
	Data         []byte
	Data2        []byte
	Counter      int64
}
```

The `Update` method is called, limiting the change to `Counter`:

```
_, err = store.Update(obj, Schema.TestModel.Counter)
```

## Unexpected Output

Before updating the counter, fill object with random bytes:

```
obj.Data: abff8e1e90dd27df343ebef523e241326bd6a1490f960d07ee3095df7f6850e0
obj.Data2: c83aa6f5aa1f489df8ccaa55eac71eb293d27637be03a55d777fefcd24796f43
```

After the update, these should be the same, but is now changed to:

```
after update obj.Data: 0001310000000135000045000000090000000000530000000431205748455245
after update obj.Data2: 2432000000440000000753330053000000047637be03a55d777fefcd24796f43
```

## Analysis

This happens only if the object is fetched from the DB using a query:

```
obj = store.MustFindOne(NewTestModelQuery().FindByID(obj.ID))
```

This DOES NOT happen if the object is created from constructor:

```
obj := NewTestModel()
```

In fact, if [line#56](https://github.com/hayeah/go-kallax-bug/blob/1027d1a56f4f198a28309513833fa02bc97d3997/model.go#L56) from the test case is removed, it works as expected.

**Comment by hayeah** [comment]
It looks like a problem stemming from the underlying database driver  `github.com/lib/pq`

Changing the *sql.DB to `github.com/jackc/pgx/stdlib` fixes the problem.

**Comment by roobre** [comment]
Thank you very much for your detailed bug report. I've just glanced over it and apparently looks like a `pq` problem which can be *worked around* from kallax. It would be nice to know if this buffer reusing thing is the expected behavior of `pq`, and if it is, then we should change `ByteArray.Scan` to copy the data from that buffer.

In any case, a test case would be appreciated in order to test the potential fixes properly. Could you submit a PR including your test for this, integrated in the kallax test suite?

**Comment by hayeah** [comment]
I think it is valid for `lib/pq` to reuse the buffer. From the [sql.Scanner](https://golang.org/pkg/database/sql/#Scanner) interface, there is a comment about `[]byte` being reused.

```
        // Reference types such as []byte are only valid until the next call to Scan
        // and should not be retained. Their underlying memory is owned by the driver.
        // If retention is necessary, copy their values before the next call to Scan.
```

**Comment by roobre** [comment]
We'll continue discussion on the PR, thank you very much!
