### ISSUE TITLE
The name kallax

### ISSUE THREAD

**Issue by md2perpe** [src-d/go-kallax#305]
Is 'kallax' named after the airport Kallax outside of Luleå in the north of Sweden?

**Comment by pihentagy** [comment]
or maybe the IKEA shelf?

https://www.ikea.com/hu/hu/catalog/categories/series/27534/

**Comment by md2perpe** [comment]
From where do you think the IKEA shelf got its name? 😉

Correcting myself: Kallax is actually the name of a place outside of Luleå, but the airport was earlier named from that place and is still informally often called Kallax.

**Comment by mcuadros** [comment]
The name of the library was named just because of the IKEA bookshelf, we were short of ideas this day.
