### ISSUE TITLE
Regenerating kallax sources: undeclared name: RepositoryStore

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-kallax#45]
If I try to regenerate the kallax.go file, I have the next error:

```
undeclared name: MyActualStore
```
where MyActualStore is the previous store generated by kallax.

**Comment by erizocosmico** [comment]
Can you provide a small example we can use to reproduce this?

**Comment by ajnavarro** [comment]
creates a kallax model ´mymodel.go´

```
type MyModel struct {
	kallax.Model `table:"repositories"`
	kallax.Timestamps
	[...]
}
```
Call to ´kallax gen´ and check  that the new ´kallax.go´ generated file exists.

Use the generated Store source code in some part of your code.

Try to run again ´kallax gen ´.
