### ISSUE TITLE
Explore using ULIDs as identifiers

### ISSUE THREAD

**Issue by erizocosmico** [src-d/go-kallax#87]
Explore using ULIDs instead of UUIDs for identifiers as they are lexically sortable (https://github.com/oklog/ulid)

Since PostgreSQL uuid type does not support ULIDs, char(size of ulid) should be required in identifier columns.

**Comment by erizocosmico** [comment]
Using ULID would require us to use `CHAR(26)` or `TEXT` instead of `UUID`, which is twice the size as an `uuid` column.

```sql
select pg_column_size('01AN4Z07BY79KA1307SR9X4MV3'::text) as text_size,                                                          pg_column_size('110ec58a-a0f2-4ac4-8393-c866d813b8d1'::uuid) as uuid_size, 
pg_column_size('01AN4Z07BY79KA1307SR9X4MV3'::char(26)) as char_size;
 text_size | uuid_size | char_size 
-----------+-----------+-----------
        30 |        16 |        30
```

**Comment by joelvh** [comment]
@erizocosmico curious what you did here. We are starting to use PostgreSQL UUID and are looking to store ULID in there. What we do is decode the ULID to integer, then integer to hex, and then we pad it with zeros (usually one zero) to get to the proper UUID length.

What are your thoughts or what did you do?
